// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: command.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from command.proto</summary>
public static partial class CommandReflection {

  #region Descriptor
  /// <summary>File descriptor for command.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CommandReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1jb21tYW5kLnByb3RvKvIFCgdDb21tYW5kEg4KCktFRVBfQUxJVkUQABII",
          "CgRSRVNQEAESCAoER0FURRACEhAKDFNFUlZFUl9TVEFURRADEhcKE1NFUlZF",
          "Ul9MSVNUX0NIQU5HRUQQBBIQCgxTRVJWRVJfUkVTRVQQBRIUChBDT05ORUNU",
          "X0dBVEVfUkVREAYSFAoQU0VTU0lPTl9DRVJUX05URhAHEg4KCkNDSEFUX0NI",
          "QVQQCBIMCghESVNQQVRDSBAJEhgKFExEX0NSRUFURV9QTEFZRVJfUkVREAoS",
          "FgoSR0RfTE9BRF9QTEFZRVJfUkVREAsSGQoVR0RfUkVMRUFTRV9QTEFZRVJf",
          "TlRGEAwSFgoSR0RfQ1JFQVRFX1JPTEVfUkVREA0SFAoQR0RfTE9BRF9ST0xF",
          "X1JFURAOEhIKDlJFTE9BRF9FVENfUkVREA8SEgoOVVBEQVRFX0VUQ19OVEYQ",
          "EBIMCghNT1ZFX05URhAREhUKEU5FQVJfRU5USVRJRVNfTlRGEBISEwoPRU5U",
          "SVRZX0RBVEFfUkVREBMSDgoKUk9MRV9FTlRFUhAUEh0KGVVQREFURV9QTEFZ",
          "RVJfQUREUkVTU19OVEYQFRIdChlSRU1PVkVfUExBWUVSX0FERFJFU1NfTlRG",
          "EBYSGgoWVVBEQVRFX01BUF9BRERSRVNTX05URhAXEhoKFlJFTU9WRV9NQVBf",
          "QUREUkVTU19OVEYQGBIXChNHRVRfTUFQX0FERFJFU1NfUkVREBkSFwoTTE9B",
          "RF9TVEFUSUNfTUFQX1JFURAaEhgKFExPQURfRFlOQU1JQ19NQVBfUkVREBsS",
          "HgoaVVBEQVRFX1NUQVRJQ19NQVBfVVVJRF9OVEYQHBIbChdHRVRfU1RBVElD",
          "X01BUF9VVUlEX1JFURAdEhcKE1NBVkVfU1RBVElDX01BUF9SRVEQHhIYChRT",
          "QVZFX0RZTkFNSUNfTUFQX1JFURAfEg0KCVNBVkVfUk9MRRAgEg4KCkdFVF9N",
          "QVBfSUQQIUIYWhZJTlNlcnZlci9zcmMvcHJvdG8vbXNnYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Command), }, null));
  }
  #endregion

}
#region Enums
public enum Command {
  /// <summary>
  /// any -> center
  /// </summary>
  [pbr::OriginalName("KEEP_ALIVE")] KeepAlive = 0,
  [pbr::OriginalName("RESP")] Resp = 1,
  /// <summary>
  /// client -> gate -> any
  /// </summary>
  [pbr::OriginalName("GATE")] Gate = 2,
  /// <summary>
  /// any -> center
  /// </summary>
  [pbr::OriginalName("SERVER_STATE")] ServerState = 3,
  /// <summary>
  /// center -> any
  /// </summary>
  [pbr::OriginalName("SERVER_LIST_CHANGED")] ServerListChanged = 4,
  /// <summary>
  /// center -> any
  /// </summary>
  [pbr::OriginalName("SERVER_RESET")] ServerReset = 5,
  /// <summary>
  /// client -> gate
  /// </summary>
  [pbr::OriginalName("CONNECT_GATE_REQ")] ConnectGateReq = 6,
  /// <summary>
  /// gate -> client
  /// </summary>
  [pbr::OriginalName("SESSION_CERT_NTF")] SessionCertNtf = 7,
  /// <summary>
  /// client -> chat
  /// </summary>
  [pbr::OriginalName("CCHAT_CHAT")] CchatChat = 8,
  /// <summary>
  /// any -> dispatcher
  /// </summary>
  [pbr::OriginalName("DISPATCH")] Dispatch = 9,
  /// <summary>
  /// login -> database
  /// </summary>
  [pbr::OriginalName("LD_CREATE_PLAYER_REQ")] LdCreatePlayerReq = 10,
  /// <summary>
  /// gate -> database
  /// </summary>
  [pbr::OriginalName("GD_LOAD_PLAYER_REQ")] GdLoadPlayerReq = 11,
  /// <summary>
  /// gate -> database
  /// </summary>
  [pbr::OriginalName("GD_RELEASE_PLAYER_NTF")] GdReleasePlayerNtf = 12,
  /// <summary>
  /// gate -> database
  /// </summary>
  [pbr::OriginalName("GD_CREATE_ROLE_REQ")] GdCreateRoleReq = 13,
  /// <summary>
  /// gate -> database
  /// </summary>
  [pbr::OriginalName("GD_LOAD_ROLE_REQ")] GdLoadRoleReq = 14,
  /// <summary>
  /// web -> center
  /// </summary>
  [pbr::OriginalName("RELOAD_ETC_REQ")] ReloadEtcReq = 15,
  /// <summary>
  /// center -> any
  /// </summary>
  [pbr::OriginalName("UPDATE_ETC_NTF")] UpdateEtcNtf = 16,
  /// <summary>
  /// client -> world
  /// </summary>
  [pbr::OriginalName("MOVE_NTF")] MoveNtf = 17,
  /// <summary>
  /// world -> client
  /// </summary>
  [pbr::OriginalName("NEAR_ENTITIES_NTF")] NearEntitiesNtf = 18,
  /// <summary>
  /// client -> world
  /// </summary>
  [pbr::OriginalName("ENTITY_DATA_REQ")] EntityDataReq = 19,
  /// <summary>
  /// client -> gate; any -> world
  /// </summary>
  [pbr::OriginalName("ROLE_ENTER")] RoleEnter = 20,
  /// <summary>
  /// any -> gps
  /// </summary>
  [pbr::OriginalName("UPDATE_PLAYER_ADDRESS_NTF")] UpdatePlayerAddressNtf = 21,
  /// <summary>
  /// gate -> gps
  /// </summary>
  [pbr::OriginalName("REMOVE_PLAYER_ADDRESS_NTF")] RemovePlayerAddressNtf = 22,
  /// <summary>
  /// world -> gps
  /// </summary>
  [pbr::OriginalName("UPDATE_MAP_ADDRESS_NTF")] UpdateMapAddressNtf = 23,
  /// <summary>
  /// world -> gps
  /// </summary>
  [pbr::OriginalName("REMOVE_MAP_ADDRESS_NTF")] RemoveMapAddressNtf = 24,
  /// <summary>
  /// database -> gps
  /// </summary>
  [pbr::OriginalName("GET_MAP_ADDRESS_REQ")] GetMapAddressReq = 25,
  /// <summary>
  /// world -> database
  /// </summary>
  [pbr::OriginalName("LOAD_STATIC_MAP_REQ")] LoadStaticMapReq = 26,
  /// <summary>
  /// world -> database
  /// </summary>
  [pbr::OriginalName("LOAD_DYNAMIC_MAP_REQ")] LoadDynamicMapReq = 27,
  /// <summary>
  /// world -> gps
  /// </summary>
  [pbr::OriginalName("UPDATE_STATIC_MAP_UUID_NTF")] UpdateStaticMapUuidNtf = 28,
  /// <summary>
  /// any -> gps
  /// </summary>
  [pbr::OriginalName("GET_STATIC_MAP_UUID_REQ")] GetStaticMapUuidReq = 29,
  /// <summary>
  /// any -> database
  /// </summary>
  [pbr::OriginalName("SAVE_STATIC_MAP_REQ")] SaveStaticMapReq = 30,
  /// <summary>
  /// any -> database
  /// </summary>
  [pbr::OriginalName("SAVE_DYNAMIC_MAP_REQ")] SaveDynamicMapReq = 31,
  /// <summary>
  /// any -> database
  /// </summary>
  [pbr::OriginalName("SAVE_ROLE")] SaveRole = 32,
  /// <summary>
  /// gate -> world
  /// </summary>
  [pbr::OriginalName("GET_MAP_ID")] GetMapId = 33,
}

#endregion


#endregion Designer generated code
