// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data.entity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from data.entity.proto</summary>
public static partial class DataEntityReflection {

  #region Descriptor
  /// <summary>File descriptor for data.entity.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DataEntityReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFkYXRhLmVudGl0eS5wcm90bxoUZGF0YS5jb21wb25lbnQucHJvdG8iRwoS",
          "RW50aXR5UmVhbHRpbWVEYXRhEhkKEUxhc3RTdGF0aWNNYXBVVUlEGAEgASgJ",
          "EhYKDkN1cnJlbnRNYXBVVUlEGAIgASgJImsKCkVudGl0eURhdGESEgoKRW50",
          "aXR5VVVJRBgBIAEoCRIpCgxSZWFsVGltZURhdGEYAiABKAsyEy5FbnRpdHlS",
          "ZWFsdGltZURhdGESHgoKQ29tcG9uZW50cxgDIAMoCzIKLkNvbXBvbmVudCpy",
          "CgpFbnRpdHlUeXBlEg0KCU9BQUVudGl0eRAAEg4KClJvbGVFbnRpdHkQARIR",
          "Cg1Nb25zdGVyRW50aXR5EAISEAoMQnVsbGV0RW50aXR5EAMSDQoJTlBDRW50",
          "aXR5EAQSEQoNVHJpZ2dlckVudGl0eRAFQhlaF0lOU2VydmVyL3NyYy9wcm90",
          "by9kYXRhYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::DataComponentReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EntityType), }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::EntityRealtimeData), global::EntityRealtimeData.Parser, new[]{ "LastStaticMapUUID", "CurrentMapUUID" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EntityData), global::EntityData.Parser, new[]{ "EntityUUID", "RealTimeData", "Components" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum EntityType {
  /// <summary>
  /// one above all
  /// </summary>
  [pbr::OriginalName("OAAEntity")] Oaaentity = 0,
  [pbr::OriginalName("RoleEntity")] RoleEntity = 1,
  [pbr::OriginalName("MonsterEntity")] MonsterEntity = 2,
  [pbr::OriginalName("BulletEntity")] BulletEntity = 3,
  [pbr::OriginalName("NPCEntity")] Npcentity = 4,
  [pbr::OriginalName("TriggerEntity")] TriggerEntity = 5,
}

#endregion

#region Messages
public sealed partial class EntityRealtimeData : pb::IMessage<EntityRealtimeData> {
  private static readonly pb::MessageParser<EntityRealtimeData> _parser = new pb::MessageParser<EntityRealtimeData>(() => new EntityRealtimeData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<EntityRealtimeData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataEntityReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityRealtimeData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityRealtimeData(EntityRealtimeData other) : this() {
    lastStaticMapUUID_ = other.lastStaticMapUUID_;
    currentMapUUID_ = other.currentMapUUID_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityRealtimeData Clone() {
    return new EntityRealtimeData(this);
  }

  /// <summary>Field number for the "LastStaticMapUUID" field.</summary>
  public const int LastStaticMapUUIDFieldNumber = 1;
  private string lastStaticMapUUID_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string LastStaticMapUUID {
    get { return lastStaticMapUUID_; }
    set {
      lastStaticMapUUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "CurrentMapUUID" field.</summary>
  public const int CurrentMapUUIDFieldNumber = 2;
  private string currentMapUUID_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string CurrentMapUUID {
    get { return currentMapUUID_; }
    set {
      currentMapUUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as EntityRealtimeData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(EntityRealtimeData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (LastStaticMapUUID != other.LastStaticMapUUID) return false;
    if (CurrentMapUUID != other.CurrentMapUUID) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (LastStaticMapUUID.Length != 0) hash ^= LastStaticMapUUID.GetHashCode();
    if (CurrentMapUUID.Length != 0) hash ^= CurrentMapUUID.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (LastStaticMapUUID.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(LastStaticMapUUID);
    }
    if (CurrentMapUUID.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CurrentMapUUID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (LastStaticMapUUID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(LastStaticMapUUID);
    }
    if (CurrentMapUUID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentMapUUID);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(EntityRealtimeData other) {
    if (other == null) {
      return;
    }
    if (other.LastStaticMapUUID.Length != 0) {
      LastStaticMapUUID = other.LastStaticMapUUID;
    }
    if (other.CurrentMapUUID.Length != 0) {
      CurrentMapUUID = other.CurrentMapUUID;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          LastStaticMapUUID = input.ReadString();
          break;
        }
        case 18: {
          CurrentMapUUID = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class EntityData : pb::IMessage<EntityData> {
  private static readonly pb::MessageParser<EntityData> _parser = new pb::MessageParser<EntityData>(() => new EntityData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<EntityData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataEntityReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityData(EntityData other) : this() {
    entityUUID_ = other.entityUUID_;
    realTimeData_ = other.realTimeData_ != null ? other.realTimeData_.Clone() : null;
    components_ = other.components_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityData Clone() {
    return new EntityData(this);
  }

  /// <summary>Field number for the "EntityUUID" field.</summary>
  public const int EntityUUIDFieldNumber = 1;
  private string entityUUID_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string EntityUUID {
    get { return entityUUID_; }
    set {
      entityUUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "RealTimeData" field.</summary>
  public const int RealTimeDataFieldNumber = 2;
  private global::EntityRealtimeData realTimeData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::EntityRealtimeData RealTimeData {
    get { return realTimeData_; }
    set {
      realTimeData_ = value;
    }
  }

  /// <summary>Field number for the "Components" field.</summary>
  public const int ComponentsFieldNumber = 3;
  private static readonly pb::FieldCodec<global::Component> _repeated_components_codec
      = pb::FieldCodec.ForMessage(26, global::Component.Parser);
  private readonly pbc::RepeatedField<global::Component> components_ = new pbc::RepeatedField<global::Component>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::Component> Components {
    get { return components_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as EntityData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(EntityData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EntityUUID != other.EntityUUID) return false;
    if (!object.Equals(RealTimeData, other.RealTimeData)) return false;
    if(!components_.Equals(other.components_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (EntityUUID.Length != 0) hash ^= EntityUUID.GetHashCode();
    if (realTimeData_ != null) hash ^= RealTimeData.GetHashCode();
    hash ^= components_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (EntityUUID.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(EntityUUID);
    }
    if (realTimeData_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(RealTimeData);
    }
    components_.WriteTo(output, _repeated_components_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (EntityUUID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityUUID);
    }
    if (realTimeData_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(RealTimeData);
    }
    size += components_.CalculateSize(_repeated_components_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(EntityData other) {
    if (other == null) {
      return;
    }
    if (other.EntityUUID.Length != 0) {
      EntityUUID = other.EntityUUID;
    }
    if (other.realTimeData_ != null) {
      if (realTimeData_ == null) {
        RealTimeData = new global::EntityRealtimeData();
      }
      RealTimeData.MergeFrom(other.RealTimeData);
    }
    components_.Add(other.components_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          EntityUUID = input.ReadString();
          break;
        }
        case 18: {
          if (realTimeData_ == null) {
            RealTimeData = new global::EntityRealtimeData();
          }
          input.ReadMessage(RealTimeData);
          break;
        }
        case 26: {
          components_.AddEntriesFrom(input, _repeated_components_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
