// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data.role.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from data.role.proto</summary>
public static partial class DataRoleReflection {

  #region Descriptor
  /// <summary>File descriptor for data.role.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DataRoleReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9kYXRhLnJvbGUucHJvdG8aEWRhdGEuZW50aXR5LnByb3RvInYKD1JvbGVT",
          "dW1tYXJ5RGF0YRIMCgROYW1lGAEgASgJEgwKBFpvbmUYAiABKAUSEAoIUm9s",
          "ZVVVSUQYAyABKAkSEgoKUGxheWVyVVVJRBgEIAEoCRIPCgdNYXBVVUlEGAUg",
          "ASgJEhAKCE1haWxVVUlEGAYgASgJIioKC1JvbGVBZGRyZXNzEgwKBEdhdGUY",
          "ASABKAUSDQoFV29ybGQYAiABKAUiMQoOUm9sZU9ubGluZURhdGESHwoKRW50",
          "aXR5RGF0YRgBIAEoCzILLkVudGl0eURhdGEiLQoQUm9sZVJlYWx0aW1lRGF0",
          "YRIZChFMYXN0U3RhdGljTWFwVVVJRBgBIAEoCSJSCgRSb2xlEiUKC1N1bW1h",
          "cnlEYXRhGAEgASgLMhAuUm9sZVN1bW1hcnlEYXRhEiMKCk9ubGluZURhdGEY",
          "AiABKAsyDy5Sb2xlT25saW5lRGF0YUIZWhdJTlNlcnZlci9zcmMvcHJvdG8v",
          "ZGF0YWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::DataEntityReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RoleSummaryData), global::RoleSummaryData.Parser, new[]{ "Name", "Zone", "RoleUUID", "PlayerUUID", "MapUUID", "MailUUID" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RoleAddress), global::RoleAddress.Parser, new[]{ "Gate", "World" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RoleOnlineData), global::RoleOnlineData.Parser, new[]{ "EntityData" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RoleRealtimeData), global::RoleRealtimeData.Parser, new[]{ "LastStaticMapUUID" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Role), global::Role.Parser, new[]{ "SummaryData", "OnlineData" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 离线数据
/// </summary>
public sealed partial class RoleSummaryData : pb::IMessage<RoleSummaryData> {
  private static readonly pb::MessageParser<RoleSummaryData> _parser = new pb::MessageParser<RoleSummaryData>(() => new RoleSummaryData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RoleSummaryData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataRoleReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleSummaryData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleSummaryData(RoleSummaryData other) : this() {
    name_ = other.name_;
    zone_ = other.zone_;
    roleUUID_ = other.roleUUID_;
    playerUUID_ = other.playerUUID_;
    mapUUID_ = other.mapUUID_;
    mailUUID_ = other.mailUUID_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleSummaryData Clone() {
    return new RoleSummaryData(this);
  }

  /// <summary>Field number for the "Name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  /// <summary>
  /// 角色名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Zone" field.</summary>
  public const int ZoneFieldNumber = 2;
  private int zone_;
  /// <summary>
  /// 游戏区
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Zone {
    get { return zone_; }
    set {
      zone_ = value;
    }
  }

  /// <summary>Field number for the "RoleUUID" field.</summary>
  public const int RoleUUIDFieldNumber = 3;
  private string roleUUID_ = "";
  /// <summary>
  /// RoleUUID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string RoleUUID {
    get { return roleUUID_; }
    set {
      roleUUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "PlayerUUID" field.</summary>
  public const int PlayerUUIDFieldNumber = 4;
  private string playerUUID_ = "";
  /// <summary>
  /// PlayerUUID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string PlayerUUID {
    get { return playerUUID_; }
    set {
      playerUUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "MapUUID" field.</summary>
  public const int MapUUIDFieldNumber = 5;
  private string mapUUID_ = "";
  /// <summary>
  /// 所在地图
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string MapUUID {
    get { return mapUUID_; }
    set {
      mapUUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "MailUUID" field.</summary>
  public const int MailUUIDFieldNumber = 6;
  private string mailUUID_ = "";
  /// <summary>
  /// 邮件地址
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string MailUUID {
    get { return mailUUID_; }
    set {
      mailUUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RoleSummaryData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RoleSummaryData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Zone != other.Zone) return false;
    if (RoleUUID != other.RoleUUID) return false;
    if (PlayerUUID != other.PlayerUUID) return false;
    if (MapUUID != other.MapUUID) return false;
    if (MailUUID != other.MailUUID) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Zone != 0) hash ^= Zone.GetHashCode();
    if (RoleUUID.Length != 0) hash ^= RoleUUID.GetHashCode();
    if (PlayerUUID.Length != 0) hash ^= PlayerUUID.GetHashCode();
    if (MapUUID.Length != 0) hash ^= MapUUID.GetHashCode();
    if (MailUUID.Length != 0) hash ^= MailUUID.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Zone != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Zone);
    }
    if (RoleUUID.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(RoleUUID);
    }
    if (PlayerUUID.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(PlayerUUID);
    }
    if (MapUUID.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(MapUUID);
    }
    if (MailUUID.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(MailUUID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Zone != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Zone);
    }
    if (RoleUUID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RoleUUID);
    }
    if (PlayerUUID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerUUID);
    }
    if (MapUUID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MapUUID);
    }
    if (MailUUID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MailUUID);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RoleSummaryData other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Zone != 0) {
      Zone = other.Zone;
    }
    if (other.RoleUUID.Length != 0) {
      RoleUUID = other.RoleUUID;
    }
    if (other.PlayerUUID.Length != 0) {
      PlayerUUID = other.PlayerUUID;
    }
    if (other.MapUUID.Length != 0) {
      MapUUID = other.MapUUID;
    }
    if (other.MailUUID.Length != 0) {
      MailUUID = other.MailUUID;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Zone = input.ReadInt32();
          break;
        }
        case 26: {
          RoleUUID = input.ReadString();
          break;
        }
        case 34: {
          PlayerUUID = input.ReadString();
          break;
        }
        case 42: {
          MapUUID = input.ReadString();
          break;
        }
        case 50: {
          MailUUID = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class RoleAddress : pb::IMessage<RoleAddress> {
  private static readonly pb::MessageParser<RoleAddress> _parser = new pb::MessageParser<RoleAddress>(() => new RoleAddress());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RoleAddress> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataRoleReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleAddress() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleAddress(RoleAddress other) : this() {
    gate_ = other.gate_;
    world_ = other.world_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleAddress Clone() {
    return new RoleAddress(this);
  }

  /// <summary>Field number for the "Gate" field.</summary>
  public const int GateFieldNumber = 1;
  private int gate_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Gate {
    get { return gate_; }
    set {
      gate_ = value;
    }
  }

  /// <summary>Field number for the "World" field.</summary>
  public const int WorldFieldNumber = 2;
  private int world_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int World {
    get { return world_; }
    set {
      world_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RoleAddress);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RoleAddress other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Gate != other.Gate) return false;
    if (World != other.World) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Gate != 0) hash ^= Gate.GetHashCode();
    if (World != 0) hash ^= World.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Gate != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Gate);
    }
    if (World != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(World);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Gate != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gate);
    }
    if (World != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(World);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RoleAddress other) {
    if (other == null) {
      return;
    }
    if (other.Gate != 0) {
      Gate = other.Gate;
    }
    if (other.World != 0) {
      World = other.World;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Gate = input.ReadInt32();
          break;
        }
        case 16: {
          World = input.ReadInt32();
          break;
        }
      }
    }
  }

}

/// <summary>
/// 在线数据
/// </summary>
public sealed partial class RoleOnlineData : pb::IMessage<RoleOnlineData> {
  private static readonly pb::MessageParser<RoleOnlineData> _parser = new pb::MessageParser<RoleOnlineData>(() => new RoleOnlineData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RoleOnlineData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataRoleReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleOnlineData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleOnlineData(RoleOnlineData other) : this() {
    entityData_ = other.entityData_ != null ? other.entityData_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleOnlineData Clone() {
    return new RoleOnlineData(this);
  }

  /// <summary>Field number for the "EntityData" field.</summary>
  public const int EntityDataFieldNumber = 1;
  private global::EntityData entityData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::EntityData EntityData {
    get { return entityData_; }
    set {
      entityData_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RoleOnlineData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RoleOnlineData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(EntityData, other.EntityData)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (entityData_ != null) hash ^= EntityData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (entityData_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(EntityData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (entityData_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(EntityData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RoleOnlineData other) {
    if (other == null) {
      return;
    }
    if (other.entityData_ != null) {
      if (entityData_ == null) {
        EntityData = new global::EntityData();
      }
      EntityData.MergeFrom(other.EntityData);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (entityData_ == null) {
            EntityData = new global::EntityData();
          }
          input.ReadMessage(EntityData);
          break;
        }
      }
    }
  }

}

/// <summary>
/// 实时数据 与场景相关的数据
/// </summary>
public sealed partial class RoleRealtimeData : pb::IMessage<RoleRealtimeData> {
  private static readonly pb::MessageParser<RoleRealtimeData> _parser = new pb::MessageParser<RoleRealtimeData>(() => new RoleRealtimeData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RoleRealtimeData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataRoleReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleRealtimeData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleRealtimeData(RoleRealtimeData other) : this() {
    lastStaticMapUUID_ = other.lastStaticMapUUID_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleRealtimeData Clone() {
    return new RoleRealtimeData(this);
  }

  /// <summary>Field number for the "LastStaticMapUUID" field.</summary>
  public const int LastStaticMapUUIDFieldNumber = 1;
  private string lastStaticMapUUID_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string LastStaticMapUUID {
    get { return lastStaticMapUUID_; }
    set {
      lastStaticMapUUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RoleRealtimeData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RoleRealtimeData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (LastStaticMapUUID != other.LastStaticMapUUID) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (LastStaticMapUUID.Length != 0) hash ^= LastStaticMapUUID.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (LastStaticMapUUID.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(LastStaticMapUUID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (LastStaticMapUUID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(LastStaticMapUUID);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RoleRealtimeData other) {
    if (other == null) {
      return;
    }
    if (other.LastStaticMapUUID.Length != 0) {
      LastStaticMapUUID = other.LastStaticMapUUID;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          LastStaticMapUUID = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class Role : pb::IMessage<Role> {
  private static readonly pb::MessageParser<Role> _parser = new pb::MessageParser<Role>(() => new Role());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Role> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataRoleReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Role() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Role(Role other) : this() {
    summaryData_ = other.summaryData_ != null ? other.summaryData_.Clone() : null;
    onlineData_ = other.onlineData_ != null ? other.onlineData_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Role Clone() {
    return new Role(this);
  }

  /// <summary>Field number for the "SummaryData" field.</summary>
  public const int SummaryDataFieldNumber = 1;
  private global::RoleSummaryData summaryData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::RoleSummaryData SummaryData {
    get { return summaryData_; }
    set {
      summaryData_ = value;
    }
  }

  /// <summary>Field number for the "OnlineData" field.</summary>
  public const int OnlineDataFieldNumber = 2;
  private global::RoleOnlineData onlineData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::RoleOnlineData OnlineData {
    get { return onlineData_; }
    set {
      onlineData_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Role);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Role other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(SummaryData, other.SummaryData)) return false;
    if (!object.Equals(OnlineData, other.OnlineData)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (summaryData_ != null) hash ^= SummaryData.GetHashCode();
    if (onlineData_ != null) hash ^= OnlineData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (summaryData_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(SummaryData);
    }
    if (onlineData_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(OnlineData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (summaryData_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(SummaryData);
    }
    if (onlineData_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(OnlineData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Role other) {
    if (other == null) {
      return;
    }
    if (other.summaryData_ != null) {
      if (summaryData_ == null) {
        SummaryData = new global::RoleSummaryData();
      }
      SummaryData.MergeFrom(other.SummaryData);
    }
    if (other.onlineData_ != null) {
      if (onlineData_ == null) {
        OnlineData = new global::RoleOnlineData();
      }
      OnlineData.MergeFrom(other.OnlineData);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (summaryData_ == null) {
            SummaryData = new global::RoleSummaryData();
          }
          input.ReadMessage(SummaryData);
          break;
        }
        case 18: {
          if (onlineData_ == null) {
            OnlineData = new global::RoleOnlineData();
          }
          input.ReadMessage(OnlineData);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
