// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: world.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from world.proto</summary>
public static partial class WorldReflection {

  #region Descriptor
  /// <summary>File descriptor for world.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static WorldReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgt3b3JsZC5wcm90bxoPZGF0YS5yb2xlLnByb3RvIjEKDFJvbGVFbnRlck5U",
          "RhIMCgRHYXRlGAEgASgFEhMKBFJvbGUYAiABKAsyBS5Sb2xlQhhaFklOU2Vy",
          "dmVyL3NyYy9wcm90by9tc2diBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::DataRoleReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RoleEnterNTF), global::RoleEnterNTF.Parser, new[]{ "Gate", "Role" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class RoleEnterNTF : pb::IMessage<RoleEnterNTF> {
  private static readonly pb::MessageParser<RoleEnterNTF> _parser = new pb::MessageParser<RoleEnterNTF>(() => new RoleEnterNTF());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RoleEnterNTF> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WorldReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleEnterNTF() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleEnterNTF(RoleEnterNTF other) : this() {
    gate_ = other.gate_;
    role_ = other.role_ != null ? other.role_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoleEnterNTF Clone() {
    return new RoleEnterNTF(this);
  }

  /// <summary>Field number for the "Gate" field.</summary>
  public const int GateFieldNumber = 1;
  private int gate_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Gate {
    get { return gate_; }
    set {
      gate_ = value;
    }
  }

  /// <summary>Field number for the "Role" field.</summary>
  public const int RoleFieldNumber = 2;
  private global::Role role_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Role Role {
    get { return role_; }
    set {
      role_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RoleEnterNTF);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RoleEnterNTF other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Gate != other.Gate) return false;
    if (!object.Equals(Role, other.Role)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Gate != 0) hash ^= Gate.GetHashCode();
    if (role_ != null) hash ^= Role.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Gate != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Gate);
    }
    if (role_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Role);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Gate != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gate);
    }
    if (role_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Role);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RoleEnterNTF other) {
    if (other == null) {
      return;
    }
    if (other.Gate != 0) {
      Gate = other.Gate;
    }
    if (other.role_ != null) {
      if (role_ == null) {
        Role = new global::Role();
      }
      Role.MergeFrom(other.Role);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Gate = input.ReadInt32();
          break;
        }
        case 18: {
          if (role_ == null) {
            Role = new global::Role();
          }
          input.ReadMessage(Role);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
